[[vice.arg]]
values = ["-joydev1", "1"]

[[vice.arg]]
values = ["-VICIIfilter", "1"]

[[vice.arg]]
values = ["!autostart-warp"]

[[vice.arg]]
values = ["!VICIIdscan"]

[[vice.arg]]
values = ["-sound"]

[[vice.arg]]
values = ["-soundrate", "48000"]
